"""Template generation from source files.

Generates concept, task, and reference markdown templates
for a feature by reading its source files. Uses Jinja2 meta
templates for structure and an optional LLM polish pass for
content quality.

Meta template resolution order:
1. Project's .help/meta_templates/ (if exists)
2. Package defaults in attune_author/meta_templates/
"""

from __future__ import annotations

import ast
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import jinja2

from attune_author.manifest import Feature, is_safe_feature_name
from attune_author.staleness import _read_frontmatter_value, compute_source_hash

logger = logging.getLogger(__name__)

#: Core progressive-depth template kinds. These form the
#: progressive disclosure path that attune-help renders:
#: concept → task → reference. They are generated by
#: default when no explicit list is passed.
_CORE_DEPTH_NAMES = ("concept", "task", "reference")

#: Problem-shaped template kinds. Documents the failure
#: modes of a feature rather than its happy path. Generated
#: only when explicitly requested via the ``depths=`` kwarg.
_PROBLEM_TEMPLATE_NAMES = (
    "error",
    "warning",
    "troubleshooting",
    "faq",
)

#: Guidance-shaped template kinds. Opinionated or
#: contextual content that sits alongside the reference
#: material: quickstarts, tips, notes, comparisons.
#: Generated only when explicitly requested via the
#: ``depths=`` kwarg.
_GUIDANCE_TEMPLATE_NAMES = (
    "quickstart",
    "tip",
    "note",
    "comparison",
)

#: All template kinds known to the generator. New kinds are
#: added here so validation and frontmatter type mapping
#: stay in one place.
_ALL_TEMPLATE_NAMES = _CORE_DEPTH_NAMES + _PROBLEM_TEMPLATE_NAMES + _GUIDANCE_TEMPLATE_NAMES

#: Backward-compatible alias. External callers historically
#: imported ``_DEPTH_NAMES`` — keep it working but map to
#: the core set.
_DEPTH_NAMES = _CORE_DEPTH_NAMES

# Package-level default meta templates
_DEFAULT_META_DIR = Path(__file__).resolve().parent / "meta_templates"


def _build_jinja_env(
    help_dir: Path | None = None,
) -> jinja2.Environment:
    """Build a Jinja2 environment with template resolution.

    Looks for meta templates in the project's .help/meta_templates/
    first, then falls back to package defaults.

    Args:
        help_dir: Path to the project's .help/ directory.

    Returns:
        Configured Jinja2 Environment.
    """
    loaders: list[jinja2.BaseLoader] = [jinja2.PackageLoader("attune_author", "meta_templates")]

    # Project-local meta templates take priority
    if help_dir:
        project_meta = help_dir / "meta_templates"
        if project_meta.is_dir():
            loaders.insert(0, jinja2.FileSystemLoader(str(project_meta)))

    loader = jinja2.ChoiceLoader(loaders)
    return jinja2.Environment(  # nosec B701 — outputs markdown, not HTML
        loader=loader,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )


@dataclass
class GeneratedTemplate:
    """Result of generating one template file.

    Attributes:
        feature: Feature name.
        depth: Template depth (concept/task/reference).
        path: Path where the file was written.
        source_hash: Hash of source files at generation time.
    """

    feature: str
    depth: str
    path: Path
    source_hash: str


@dataclass
class GenerationResult:
    """Result of generating templates for a feature.

    Attributes:
        feature: Feature name.
        templates: List of generated template files.
        source_hash: Hash of source files.
        matched_files: Source files that were read.
    """

    feature: str
    templates: list[GeneratedTemplate] = field(default_factory=list)
    source_hash: str = ""
    matched_files: list[str] = field(default_factory=list)


def generate_feature_templates(
    feature: Feature,
    help_dir: str | Path,
    project_root: str | Path,
    depths: list[str] | None = None,
    overwrite: bool = False,
) -> GenerationResult:
    """Generate help templates for a feature.

    Creates one or more template files in the feature's
    template directory. By default emits the three core
    progressive-depth templates (concept, task, reference).
    Callers can opt into two additional template groups by
    passing an explicit ``depths`` list:

    - **Problem-shaped** kinds document failure modes
      rather than the happy path: error, warning,
      troubleshooting, faq.
    - **Guidance-shaped** kinds sit alongside the
      reference material with opinionated or contextual
      content: quickstart, tip, note, comparison.

    Files with ``status: manual`` in frontmatter are
    skipped unless ``overwrite=True``.

    Args:
        feature: The feature to generate for.
        help_dir: Path to the .help/ directory.
        project_root: Project root for resolving globs.
        depths: Which template kinds to generate. Defaults
            to the core set (concept, task, reference).
            Pass an explicit list to include any of:
            concept, task, reference, error, warning,
            troubleshooting, faq, quickstart, tip, note,
            comparison.
        overwrite: If True, overwrite manual templates.

    Returns:
        GenerationResult with paths and metadata.
    """
    help_path = Path(help_dir)
    root = Path(project_root)
    target_depths = depths or list(_CORE_DEPTH_NAMES)

    if not is_safe_feature_name(feature.name):
        raise ValueError(f"Invalid feature name: {feature.name!r}")

    # Compute source hash
    source_hash, matched_files = compute_source_hash(feature, root)

    # Extract info from source files
    source_info = _extract_source_info(matched_files, root)

    result = GenerationResult(
        feature=feature.name,
        source_hash=source_hash,
        matched_files=matched_files,
    )

    template_dir = help_path / "templates" / feature.name
    template_dir.mkdir(parents=True, exist_ok=True)

    # Build Jinja2 environment with project-first resolution
    env = _build_jinja_env(help_path)

    for depth in target_depths:
        if depth not in _ALL_TEMPLATE_NAMES:
            logger.warning("Unknown template kind '%s', skipping", depth)
            continue

        out_path = template_dir / f"{depth}.md"

        # Respect manual templates
        if out_path.exists() and not overwrite:
            if _is_manual(out_path):
                logger.info(
                    "Skipping %s/%s.md (status: manual)",
                    feature.name,
                    depth,
                )
                continue

        content = _render_template(
            env=env,
            feature=feature,
            depth=depth,
            source_hash=source_hash,
            source_info=source_info,
        )

        # LLM polish pass — improves writing quality
        content = _maybe_polish(
            content,
            feature,
            source_info,
            template_type=depth,
        )

        out_path.write_text(content, encoding="utf-8")
        result.templates.append(
            GeneratedTemplate(
                feature=feature.name,
                depth=depth,
                path=out_path,
                source_hash=source_hash,
            )
        )

    return result


def _maybe_polish(
    content: str,
    feature: Feature,
    source_info: _SourceInfo,
    template_type: str = "generic",
) -> str:
    """Run the LLM polish pass on rendered template content.

    Polish is strict by default: a missing API key or any
    LLM-call failure raises
    :class:`attune_author.polish.PolishError`. Callers that
    genuinely need to run without credentials (CI, tests)
    opt out via ``ATTUNE_AUTHOR_STRICT_POLISH=false`` — at
    which point the Jinja2 output is returned as-is.

    The summary passed to the polish pass is built from the
    enriched signature lists on ``source_info`` when
    available, so the LLM sees typed function and method
    signatures rather than bare names.

    Args:
        content: Jinja2-rendered template content.
        feature: The feature being documented.
        source_info: Extracted source information.
        template_type: Template kind (concept/task/reference
            /error/warning/troubleshooting/faq) — drives
            per-type system-prompt selection in polish.py.

    Returns:
        Polished content. In lenient mode (opt-in), returns
        the original input if the polish call failed.
    """
    from attune_author.polish import build_source_summary, polish_template

    summary = build_source_summary(
        public_classes=source_info.public_classes,
        public_functions=source_info.public_functions,
        module_docstrings=source_info.module_docstrings,
        file_count=source_info.file_count,
        function_signatures=source_info.function_signatures or None,
        class_signatures=source_info.class_signatures or None,
    )

    return polish_template(
        content,
        feature.name,
        summary,
        template_type=template_type,
    )


def _is_manual(path: Path) -> bool:
    """Check if a template has status: manual in frontmatter.

    Args:
        path: Path to the template file.

    Returns:
        True if the template is hand-written.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        logger.debug("Cannot read %s while checking manual status: %s", path, exc)
        return False

    return _read_frontmatter_value(text, "status") == "manual"


@dataclass
class _SourceInfo:
    """Extracted information from source files.

    Attributes:
        public_functions: Legacy list of ``{name, doc, file}``
            dicts. Kept for template rendering compatibility.
        public_classes: Legacy list of ``{name, doc, file}``
            dicts for classes.
        module_docstrings: First lines of module docstrings.
        config_keys: Top-level config constants discovered
            in source files.
        file_count: Number of source files matched.
        function_signatures: Enriched view of functions that
            includes formatted signatures (``name(arg: T) ->
            R``). Populated alongside ``public_functions`` so
            the polish pass can feed the LLM typed context
            without changing existing callers.
        class_signatures: Enriched view of classes with
            public method signatures joined by newlines.
    """

    public_functions: list[dict[str, str]] = field(default_factory=list)
    public_classes: list[dict[str, str]] = field(default_factory=list)
    module_docstrings: list[str] = field(default_factory=list)
    config_keys: list[str] = field(default_factory=list)
    file_count: int = 0
    function_signatures: list[dict[str, str]] = field(default_factory=list)
    class_signatures: list[dict[str, str]] = field(default_factory=list)


def _extract_source_info(
    matched_files: list[str],
    project_root: Path,
) -> _SourceInfo:
    """Extract public API info from Python source files.

    Reads AST to find public functions, classes, and
    module docstrings. Non-Python files are counted
    but not parsed.

    Args:
        matched_files: Relative paths to source files.
        project_root: Project root directory.

    Returns:
        Extracted source information.
    """
    info = _SourceInfo(file_count=len(matched_files))

    for rel_path in matched_files:
        if not rel_path.endswith(".py"):
            continue

        full_path = project_root / rel_path
        try:
            source = full_path.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=rel_path)
        except (OSError, SyntaxError) as e:
            logger.debug("Cannot parse %s: %s", rel_path, e)
            continue

        # Module docstring
        docstring = ast.get_docstring(tree)
        if docstring:
            first_line = docstring.split("\n")[0].strip()
            if first_line:
                info.module_docstrings.append(first_line)

        # Public functions and classes
        for node in ast.iter_child_nodes(tree):
            if isinstance(
                node, ast.FunctionDef | ast.AsyncFunctionDef
            ) and not node.name.startswith("_"):
                doc = ast.get_docstring(node) or ""
                first_line = doc.split("\n")[0].strip() if doc else ""
                info.public_functions.append(
                    {"name": node.name, "doc": first_line, "file": rel_path}
                )
                info.function_signatures.append(
                    {
                        "name": node.name,
                        "signature": _format_function_signature(node),
                        "doc": first_line,
                        "file": rel_path,
                    }
                )
            elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                doc = ast.get_docstring(node) or ""
                first_line = doc.split("\n")[0].strip() if doc else ""
                info.public_classes.append({"name": node.name, "doc": first_line, "file": rel_path})
                info.class_signatures.append(
                    {
                        "name": node.name,
                        "methods": _format_class_methods(node),
                        "doc": first_line,
                        "file": rel_path,
                    }
                )

    return info


def _format_function_signature(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> str:
    """Format a function AST node as a readable signature.

    Produces ``name(arg1: T1, arg2: T2 = default) -> R`` —
    good enough for the LLM to understand argument types
    and defaults without running a full unparse. Missing
    annotations are omitted rather than replaced with
    ``Any``.

    Args:
        node: AST function node.

    Returns:
        Human-readable signature string.
    """
    args: list[str] = []

    posonly = list(node.args.posonlyargs)
    regular = list(node.args.args)
    kwonly = list(node.args.kwonlyargs)
    defaults = list(node.args.defaults)
    kw_defaults = list(node.args.kw_defaults)

    # Map positional/regular args to their defaults
    positional = posonly + regular
    num_no_default = len(positional) - len(defaults)
    for idx, arg in enumerate(positional):
        arg_str = arg.arg
        if arg.annotation is not None:
            arg_str += f": {_unparse_annotation(arg.annotation)}"
        if idx >= num_no_default:
            default = defaults[idx - num_no_default]
            arg_str += f" = {_unparse_annotation(default)}"
        args.append(arg_str)
        if posonly and arg is posonly[-1] and idx == len(posonly) - 1:
            args.append("/")

    if node.args.vararg is not None:
        vararg = node.args.vararg
        vararg_str = f"*{vararg.arg}"
        if vararg.annotation is not None:
            vararg_str += f": {_unparse_annotation(vararg.annotation)}"
        args.append(vararg_str)
    elif kwonly:
        args.append("*")

    for kw_arg, kw_default in zip(kwonly, kw_defaults, strict=False):
        kw_str = kw_arg.arg
        if kw_arg.annotation is not None:
            kw_str += f": {_unparse_annotation(kw_arg.annotation)}"
        if kw_default is not None:
            kw_str += f" = {_unparse_annotation(kw_default)}"
        args.append(kw_str)

    if node.args.kwarg is not None:
        kwarg = node.args.kwarg
        kwarg_str = f"**{kwarg.arg}"
        if kwarg.annotation is not None:
            kwarg_str += f": {_unparse_annotation(kwarg.annotation)}"
        args.append(kwarg_str)

    sig = f"{node.name}({', '.join(args)})"
    if node.returns is not None:
        sig += f" -> {_unparse_annotation(node.returns)}"
    return sig


def _format_class_methods(node: ast.ClassDef) -> str:
    """Format a class's public method signatures.

    Returns a newline-separated string of signatures for
    methods whose names do not start with an underscore.
    Includes ``__init__`` because callers need to know the
    constructor shape.

    Args:
        node: AST class node.

    Returns:
        Newline-separated method signatures, or the empty
        string if the class has no public methods.
    """
    methods: list[str] = []
    for child in node.body:
        if isinstance(child, ast.FunctionDef | ast.AsyncFunctionDef):
            name = child.name
            if name.startswith("_") and name != "__init__":
                continue
            methods.append(_format_function_signature(child))
    return "\n".join(methods)


def _unparse_annotation(node: ast.expr) -> str:
    """Convert an AST expression to a readable string.

    Falls back to ``<expr>`` if ``ast.unparse`` fails so
    signature extraction never raises on exotic annotations.

    Args:
        node: AST expression node.

    Returns:
        Readable string representation.
    """
    try:
        return ast.unparse(node)
    except Exception:  # noqa: BLE001
        # INTENTIONAL: signature extraction is best-effort
        # context for the LLM — never block generation on
        # an exotic annotation we can't render.
        return "<expr>"


def _render_template(
    env: jinja2.Environment,
    feature: Feature,
    depth: str,
    source_hash: str,
    source_info: _SourceInfo,
) -> str:
    """Render a help template using Jinja2 meta templates.

    Args:
        env: Jinja2 environment with template search paths.
        feature: The feature.
        depth: concept, task, or reference.
        source_hash: SHA-256 of source files.
        source_info: Extracted source information.

    Returns:
        Markdown string with YAML frontmatter.
    """
    now = datetime.now(timezone.utc).isoformat()
    title = feature.name.replace("-", " ").replace("_", " ").title()

    # Emit both ``type`` (the canonical field attune-help
    # reads when discriminating template kinds) and ``depth``
    # (legacy field kept for backward compatibility with
    # anything reading older generated output).
    frontmatter = (
        f"---\n"
        f"type: {depth}\n"
        f"feature: {feature.name}\n"
        f"depth: {depth}\n"
        f"generated_at: {now}\n"
        f"source_hash: {source_hash}\n"
        f"status: generated\n"
        f"---\n"
    )

    template = env.get_template(f"{depth}.md.j2")
    body = template.render(
        title=title,
        feature_name=feature.name,
        description=feature.description,
        file_patterns=feature.files,
        tags=feature.tags,
        public_classes=source_info.public_classes,
        public_functions=source_info.public_functions,
        module_docstrings=source_info.module_docstrings,
        config_keys=source_info.config_keys,
        file_count=source_info.file_count,
    )

    # Strip trailing whitespace per line to avoid
    # perpetual pre-commit failures
    body = "\n".join(line.rstrip() for line in body.splitlines())

    result = frontmatter + "\n" + body
    if not result.endswith("\n"):
        result += "\n"
    return result
