"""Template generation from source files.

Generates concept, task, and reference markdown templates
for a feature by reading its source files. Uses Jinja2 meta
templates for structure and an optional LLM polish pass for
content quality.

Meta template resolution order:
1. Project's .help/meta_templates/ (if exists)
2. Package defaults in attune_author/meta_templates/
"""

from __future__ import annotations

import ast
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import jinja2

from attune_author.manifest import Feature, is_safe_feature_name
from attune_author.staleness import _read_frontmatter_value, compute_source_hash

logger = logging.getLogger(__name__)

#: Cap on concurrent LLM calls during the parallel polish phase.
#: Sized to comfortably fit under Anthropic's per-minute rate
#: limits while still saturating the LLM-bound wall time of a
#: typical ``regenerate --all-kinds`` run.
_POLISH_MAX_WORKERS = 4


def _parallel_polish(
    pending: list[tuple[str, str, Path]],
    feature: object,
    source_info: object,
    use_rag: bool,
) -> dict[str, tuple[str, Path]]:
    """Polish a batch of rendered templates concurrently.

    Args:
        pending: List of (depth, rendered_content, out_path) tuples.
        feature: Feature being documented (read-only, thread-safe).
        source_info: Extracted source info (read-only, thread-safe).
        use_rag: Whether to use RAG grounding during polish.

    Returns:
        Mapping of depth -> (polished_content, out_path). Raises
        the first exception encountered (propagated from the future).
    """

    def _task(depth: str, content: str, out_path: Path) -> tuple[str, str, Path]:
        polished = _maybe_polish(
            content,
            feature,  # type: ignore[arg-type]
            source_info,  # type: ignore[arg-type]
            template_type=depth,
            use_rag=use_rag,
        )
        return depth, polished, out_path

    results: dict[str, tuple[str, Path]] = {}
    workers = min(len(pending), _POLISH_MAX_WORKERS)
    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = {
            executor.submit(_task, depth, content, out_path): depth
            for depth, content, out_path in pending
        }
        for future in as_completed(futures):
            depth, polished, out_path = future.result()
            results[depth] = (polished, out_path)
    return results


#: Core progressive-depth template kinds. These form the
#: progressive disclosure path that attune-help renders:
#: concept → task → reference. They are generated by
#: default when no explicit list is passed.
_CORE_DEPTH_NAMES = ("concept", "task", "reference")

#: Problem-shaped template kinds. Documents the failure
#: modes of a feature rather than its happy path. Generated
#: only when explicitly requested via the ``depths=`` kwarg.
_PROBLEM_TEMPLATE_NAMES = (
    "error",
    "warning",
    "troubleshooting",
    "faq",
)

#: Guidance-shaped template kinds. Opinionated or
#: contextual content that sits alongside the reference
#: material: quickstarts, tips, notes, comparisons.
#: Generated only when explicitly requested via the
#: ``depths=`` kwarg.
_GUIDANCE_TEMPLATE_NAMES = (
    "quickstart",
    "tip",
    "note",
    "comparison",
)

#: Project-doc kinds — output to docs/ instead of
#: .help/templates/. These use an HTML comment footer
#: for staleness tracking instead of YAML frontmatter.
#: Generated only when explicitly requested via the
#: ``depths=`` kwarg.
_PROJECT_DOC_NAMES = (
    "how-to",
    "tutorial",
    "cli-reference",
    "architecture",
)

#: All template kinds known to the generator. New kinds are
#: added here so validation and frontmatter type mapping
#: stay in one place.
_ALL_TEMPLATE_NAMES = (
    _CORE_DEPTH_NAMES + _PROBLEM_TEMPLATE_NAMES + _GUIDANCE_TEMPLATE_NAMES + _PROJECT_DOC_NAMES
)

#: Backward-compatible alias. External callers historically
#: imported ``_DEPTH_NAMES`` — keep it working but map to
#: the core set.
_DEPTH_NAMES = _CORE_DEPTH_NAMES

# Package-level default meta templates
_DEFAULT_META_DIR = Path(__file__).resolve().parent / "meta_templates"


def _build_jinja_env(
    help_dir: Path | None = None,
) -> jinja2.Environment:
    """Build a Jinja2 environment with template resolution.

    Looks for meta templates in the project's .help/meta_templates/
    first, then falls back to package defaults.

    Args:
        help_dir: Path to the project's .help/ directory.

    Returns:
        Configured Jinja2 Environment.
    """
    loaders: list[jinja2.BaseLoader] = [jinja2.PackageLoader("attune_author", "meta_templates")]

    # Project-local meta templates take priority
    if help_dir:
        project_meta = help_dir / "meta_templates"
        if project_meta.is_dir():
            loaders.insert(0, jinja2.FileSystemLoader(str(project_meta)))

    loader = jinja2.ChoiceLoader(loaders)
    return jinja2.Environment(  # nosec B701 — outputs markdown, not HTML
        loader=loader,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )


@dataclass
class GeneratedTemplate:
    """Result of generating one template file.

    Attributes:
        feature: Feature name.
        depth: Template depth (concept/task/reference).
        path: Path where the file was written.
        source_hash: Hash of source files at generation time.
    """

    feature: str
    depth: str
    path: Path
    source_hash: str


@dataclass(frozen=True)
class _PendingPolish:
    """One depth pre-polish state.

    Returned by :func:`prepare_polish_phase` so the batch path
    can submit polish requests for many features at once and
    splice results back via :func:`apply_polish_results`.
    """

    depth: str
    rendered_content: str
    out_path: Path


@dataclass(frozen=True)
class PolishPreparation:
    """Per-feature pre-polish state for the batch path.

    Encapsulates everything :func:`generate_feature_templates`
    computes BEFORE the polish pass so a sibling caller (the
    batch maintenance flow) can collect prompts across many
    features, submit one batch, and later splice polished
    results back without re-doing the expensive Phase 1 work.

    The synchronous path does not use this — it stays inside
    ``generate_feature_templates`` as today.
    """

    feature: object  # Feature; kept loosely-typed to avoid import cycle
    source_hash: str
    matched_files: list[str]
    source_info: object  # _SourceInfo; ditto
    pending: tuple[_PendingPolish, ...]
    use_rag: bool

    def pending_legacy_tuples(self) -> tuple[tuple[str, str, Path], ...]:
        """Adapt ``pending`` to the legacy 3-tuple shape for ``_parallel_polish``.

        ``_parallel_polish`` predates this dataclass and expects
        ``(depth, content, out_path)``. We keep the legacy shape
        local to this conversion so the rest of the code can use
        the more readable :class:`_PendingPolish`.
        """
        return tuple((p.depth, p.rendered_content, p.out_path) for p in self.pending)


@dataclass
class GenerationResult:
    """Result of generating templates for a feature.

    Attributes:
        feature: Feature name.
        templates: List of generated template files.
        source_hash: Hash of source files.
        matched_files: Source files that were read.
    """

    feature: str
    templates: list[GeneratedTemplate] = field(default_factory=list)
    source_hash: str = ""
    matched_files: list[str] = field(default_factory=list)


def generate_feature_templates(
    feature: Feature,
    help_dir: str | Path,
    project_root: str | Path,
    depths: list[str] | None = None,
    overwrite: bool = False,
    use_rag: bool = True,
) -> GenerationResult:
    """Generate help templates for a feature.

    Creates one or more template files in the feature's
    template directory. By default emits the three core
    progressive-depth templates (concept, task, reference).
    Callers can opt into two additional template groups by
    passing an explicit ``depths`` list:

    - **Problem-shaped** kinds document failure modes
      rather than the happy path: error, warning,
      troubleshooting, faq.
    - **Guidance-shaped** kinds sit alongside the
      reference material with opinionated or contextual
      content: quickstart, tip, note, comparison.
    - **Project-doc** kinds output to ``docs/`` instead of
      ``.help/templates/`` and use an HTML comment footer
      for staleness tracking instead of YAML frontmatter:
      how-to, tutorial, cli-reference, architecture.

    ``.help/`` files with ``status: manual`` in frontmatter
    are skipped unless ``overwrite=True``. Project-doc files
    that already exist on disk are also skipped unless
    ``overwrite=True``.

    Args:
        feature: The feature to generate for.
        help_dir: Path to the .help/ directory.
        project_root: Project root for resolving globs.
        depths: Which template kinds to generate. Defaults
            to the core set (concept, task, reference).
            Pass an explicit list to include any of:
            concept, task, reference, error, warning,
            troubleshooting, faq, quickstart, tip, note,
            comparison, how-to, tutorial, cli-reference,
            architecture.
        overwrite: If True, overwrite manual and existing
            project-doc templates.

    Returns:
        GenerationResult with paths and metadata.
    """
    prep = prepare_polish_phase(
        feature=feature,
        help_dir=help_dir,
        project_root=project_root,
        depths=depths,
        overwrite=overwrite,
        use_rag=use_rag,
    )

    # Phase 2: LLM polish — run all depths concurrently.
    polished = _parallel_polish(
        list(prep.pending_legacy_tuples()),
        prep.feature,
        prep.source_info,
        prep.use_rag,
    )
    polished_text: dict[str, str] = {depth: text for depth, (text, _path) in polished.items()}

    return apply_polish_results(prep, polished_text)


def prepare_polish_phase(
    feature: Feature,
    help_dir: str | Path,
    project_root: str | Path,
    depths: list[str] | None = None,
    overwrite: bool = False,
    use_rag: bool = True,
) -> PolishPreparation:
    """Run the pre-polish (Phase 1) work for one feature.

    Computes the source hash, extracts source info, builds the
    Jinja environment, renders all active templates, and returns
    a :class:`PolishPreparation` carrying everything the polish
    phase (and later the write phase) need.

    Pure of LLM calls. Both the synchronous path
    (:func:`generate_feature_templates`) and the batched path
    (:mod:`attune_author.maintenance_batch`) call this so they
    render identically — the parity guard against drift.
    """
    help_path = Path(help_dir)
    root = Path(project_root)
    target_depths = depths or list(_CORE_DEPTH_NAMES)

    if not is_safe_feature_name(feature.name):
        raise ValueError(f"Invalid feature name: {feature.name!r}")

    source_hash, matched_files = compute_source_hash(feature, root)
    source_info = _extract_source_info(matched_files, root)

    template_dir = help_path / "templates" / feature.name
    template_dir.mkdir(parents=True, exist_ok=True)

    env = _build_jinja_env(help_path)

    if (
        any(d in _PROJECT_DOC_NAMES and d != "architecture" for d in target_depths)
        and len(feature.doc_paths) > 1
    ):
        logger.warning(
            "Feature '%s' has %d doc_paths; only the first (%s) is generated. "
            "Remaining paths (%s) are tracked by staleness but not written. "
            "Multi-path project-doc generation is a planned follow-on.",
            feature.name,
            len(feature.doc_paths),
            feature.doc_paths[0],
            ", ".join(feature.doc_paths[1:]),
        )

    pending: list[_PendingPolish] = []
    for depth in target_depths:
        if depth not in _ALL_TEMPLATE_NAMES:
            logger.warning("Unknown template kind '%s', skipping", depth)
            continue

        is_project_doc = depth in _PROJECT_DOC_NAMES

        if is_project_doc:
            out_path = _project_doc_output_path(depth, feature, root)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            if out_path.exists() and not overwrite:
                logger.info(
                    "Skipping %s (%s exists, use --overwrite to regenerate)",
                    out_path,
                    depth,
                )
                continue
        else:
            out_path = template_dir / f"{depth}.md"
            if out_path.exists() and not overwrite:
                if _is_manual(out_path):
                    logger.info(
                        "Skipping %s/%s.md (status: manual)",
                        feature.name,
                        depth,
                    )
                    continue

        if is_project_doc:
            content = _render_project_doc_template(
                env=env,
                feature=feature,
                depth=depth,
                source_hash=source_hash,
                source_info=source_info,
            )
        else:
            content = _render_template(
                env=env,
                feature=feature,
                depth=depth,
                source_hash=source_hash,
                source_info=source_info,
            )
        pending.append(_PendingPolish(depth=depth, rendered_content=content, out_path=out_path))

    return PolishPreparation(
        feature=feature,
        source_hash=source_hash,
        matched_files=matched_files,
        source_info=source_info,
        pending=tuple(pending),
        use_rag=use_rag,
    )


def apply_polish_results(
    prep: PolishPreparation,
    polished_by_depth: dict[str, str],
) -> GenerationResult:
    """Write polished content for each pending template (Phase 3).

    ``polished_by_depth`` maps depth → polished markdown. Any
    depth missing from the map falls back to the original
    rendered content — used by the batch path when a per-request
    failure means we couldn't get a polished version, mirroring
    the synchronous path's "use raw template on lenient-mode
    failure" behavior.
    """
    feature = prep.feature
    result = GenerationResult(
        feature=feature.name,
        source_hash=prep.source_hash,
        matched_files=list(prep.matched_files),
    )
    for entry in prep.pending:
        final_content = polished_by_depth.get(entry.depth, entry.rendered_content)
        entry.out_path.write_text(final_content, encoding="utf-8")
        result.templates.append(
            GeneratedTemplate(
                feature=feature.name,
                depth=entry.depth,
                path=entry.out_path,
                source_hash=prep.source_hash,
            )
        )
    return result


def _maybe_polish(
    content: str,
    feature: Feature,
    source_info: _SourceInfo,
    template_type: str = "generic",
    use_rag: bool = True,
) -> str:
    """Run the LLM polish pass on rendered template content.

    Polish is strict by default: a missing API key or any
    LLM-call failure raises
    :class:`attune_author.polish.PolishError`. Callers that
    genuinely need to run without credentials (CI, tests)
    opt out via ``ATTUNE_AUTHOR_STRICT_POLISH=false`` — at
    which point the Jinja2 output is returned as-is.

    The summary passed to the polish pass is built from the
    enriched signature lists on ``source_info`` when
    available, so the LLM sees typed function and method
    signatures rather than bare names.

    Args:
        content: Jinja2-rendered template content.
        feature: The feature being documented.
        source_info: Extracted source information.
        template_type: Template kind (concept/task/reference
            /error/warning/troubleshooting/faq) — drives
            per-type system-prompt selection in polish.py.

    Returns:
        Polished content. In lenient mode (opt-in), returns
        the original input if the polish call failed.
    """
    from attune_author.polish import build_source_summary, polish_template

    summary = build_source_summary(
        public_classes=source_info.public_classes,
        public_functions=source_info.public_functions,
        module_docstrings=source_info.module_docstrings,
        file_count=source_info.file_count,
        function_signatures=source_info.function_signatures or None,
        class_signatures=source_info.class_signatures or None,
        module_constants=source_info.module_constants or None,
    )

    augmented_context: str | None = None
    if use_rag:
        # Opt-in grounding via attune-rag. Returns None when
        # the [rag] extra isn't installed, the env var disables
        # it, or retrieval doesn't find relevant templates —
        # in any of those cases polish proceeds unchanged.
        from attune_author.rag_hook import ground_polish_context

        augmented_context = ground_polish_context(
            feature.name,
            template_type,
        )

    return polish_template(
        content,
        feature.name,
        summary,
        template_type=template_type,
        augmented_context=augmented_context,
    )


def _is_manual(path: Path) -> bool:
    """Check if a template has status: manual in frontmatter.

    Args:
        path: Path to the template file.

    Returns:
        True if the template is hand-written.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        logger.debug("Cannot read %s while checking manual status: %s", path, exc)
        return False

    return _read_frontmatter_value(text, "status") == "manual"


#: Maps each project-doc kind to its default docs/ subdirectory.
_PROJECT_DOC_KIND_SUBDIRS: dict[str, str] = {
    "how-to": "how-to",
    "tutorial": "tutorials",
    "cli-reference": "reference",
    "architecture": "architecture",
}


def _project_doc_output_path(
    kind: str,
    feature: Feature,
    project_root: Path,
) -> Path:
    """Compute the output path for a project-doc kind.

    Respects ``arch_path`` (for the architecture kind) and uses the
    primary entry of ``doc_paths`` (for other project-doc kinds) from
    the feature manifest when set. The primary doc is
    ``feature.doc_paths[0]`` (also available as ``feature.doc_path``
    for backward compatibility). Features with multiple doc paths are
    not yet supported here — bulk generation across the full list is
    a follow-on feature. Falls back to
    ``docs/<subdir>/<feature-name>.md`` relative to ``project_root``.

    Args:
        kind: Template kind (one of ``_PROJECT_DOC_NAMES``).
        feature: The feature being documented.
        project_root: Project root directory.

    Returns:
        Absolute Path where the doc file should be written.
    """
    if kind == "architecture" and feature.arch_path:
        return project_root / feature.arch_path
    if kind != "architecture" and feature.doc_path:
        return project_root / feature.doc_path
    subdir = _PROJECT_DOC_KIND_SUBDIRS.get(kind, kind)
    return project_root / "docs" / subdir / f"{feature.name}.md"


def _render_project_doc_template(
    env: jinja2.Environment,
    feature: Feature,
    depth: str,
    source_hash: str,
    source_info: _SourceInfo,
) -> str:
    """Render a project-level docs template with an HTML comment footer.

    Unlike ``.help/`` templates, project-doc kinds do not use YAML
    frontmatter. Staleness tracking uses an HTML comment appended at
    the end of the file so it does not pollute the rendered output.

    Args:
        env: Jinja2 environment with template search paths.
        feature: The feature being documented.
        depth: Template kind (one of ``_PROJECT_DOC_NAMES``).
        source_hash: SHA-256 of source files at generation time.
        source_info: Extracted source information.

    Returns:
        Markdown string with HTML comment footer and no YAML
        frontmatter.
    """
    title = feature.name.replace("-", " ").replace("_", " ").title()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    template = env.get_template(f"{depth}.md.j2")
    body = template.render(
        title=title,
        feature_name=feature.name,
        description=feature.description,
        file_patterns=feature.files,
        tags=feature.tags,
        public_classes=source_info.public_classes,
        public_functions=source_info.public_functions,
        module_docstrings=source_info.module_docstrings,
        config_keys=source_info.config_keys,
        file_count=source_info.file_count,
    )

    body = "\n".join(line.rstrip() for line in body.splitlines())

    footer = (
        f"\n<!-- attune-generated:"
        f" source_hash={source_hash}"
        f" feature={feature.name}"
        f" kind={depth}"
        f" generated_at={generated_at} -->"
    )

    result = body + footer
    if not result.endswith("\n"):
        result += "\n"
    return result


@dataclass
class _SourceInfo:
    """Extracted information from source files.

    Attributes:
        public_functions: Legacy list of ``{name, doc, file}``
            dicts. Kept for template rendering compatibility.
        public_classes: Legacy list of ``{name, doc, file}``
            dicts for classes.
        module_docstrings: First lines of module docstrings.
        config_keys: Top-level config constants discovered
            in source files.
        file_count: Number of source files matched.
        function_signatures: Enriched view of functions that
            includes formatted signatures (``name(arg: T) ->
            R``). Populated alongside ``public_functions`` so
            the polish pass can feed the LLM typed context
            without changing existing callers.
        class_signatures: Enriched view of classes with
            public method signatures joined by newlines.
    """

    public_functions: list[dict[str, str]] = field(default_factory=list)
    public_classes: list[dict[str, str]] = field(default_factory=list)
    module_docstrings: list[str] = field(default_factory=list)
    config_keys: list[str] = field(default_factory=list)
    file_count: int = 0
    function_signatures: list[dict[str, str]] = field(default_factory=list)
    class_signatures: list[dict[str, str]] = field(default_factory=list)
    module_constants: list[dict[str, object]] = field(default_factory=list)


def _docstring_first_line(node: ast.AST) -> str:
    """Return the first non-empty line of an AST node's docstring."""
    doc = ast.get_docstring(node) or ""
    return doc.split("\n", 1)[0].strip()


def _exception_name(exc: ast.expr) -> str | None:
    """Return the dotted name of an exception expression, or None."""
    if isinstance(exc, ast.Call):
        return _exception_name(exc.func)
    if isinstance(exc, ast.Name):
        return exc.id
    if isinstance(exc, ast.Attribute):
        parts: list[str] = []
        cur: ast.expr = exc
        while isinstance(cur, ast.Attribute):
            parts.append(cur.attr)
            cur = cur.value
        if isinstance(cur, ast.Name):
            parts.append(cur.id)
            return ".".join(reversed(parts))
    return None


def _raise_message(exc: ast.expr) -> str:
    """Return the literal message text of a ``raise X(...)``, or "".

    Handles three shapes:

    - ``raise X("literal")`` → ``"literal"``
    - ``raise X(f"Invalid name: {name!r}")`` → ``"Invalid name: {...}"``
      (literal prefix preserved, computed parts replaced with ``{...}``
      so the diagnostic stem callers grep for is still verifiable)
    - Anything else (computed expression, variable, no args) → ``""``

    The diagnostic stem is what reference pages want to surface:
    ``"Invalid feature name:"`` is the part users recognize when
    debugging, and it's verifiable from source.
    """
    if not isinstance(exc, ast.Call) or not exc.args:
        return ""
    first = exc.args[0]
    if isinstance(first, ast.Constant) and isinstance(first.value, str):
        return first.value
    if isinstance(first, ast.JoinedStr):
        parts: list[str] = []
        for v in first.values:
            if isinstance(v, ast.Constant) and isinstance(v.value, str):
                parts.append(v.value)
            else:
                parts.append("{...}")
        return "".join(parts)
    return ""


def _extract_raises(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> list[dict[str, str]]:
    """Exceptions raised in a function body, in source order.

    Returns a list of ``{"class_name", "message"}`` dicts — one
    per unique (class_name, message) pair in source order. A single
    function can raise the same exception class with several
    different literal messages (e.g. ``validate_file_path`` raises
    ``ValueError`` with a different diagnostic in each guard
    clause); each distinct message becomes its own entry so the
    rendered reference can list every diagnostic the caller might
    see. Exact duplicate pairs within the same function are
    collapsed.

    Bare ``raise`` (re-raise) statements are ignored because they
    rethrow whatever the current exception handler caught — which
    is not a signature-level fact.
    """
    # Pre-order DFS via iter_child_nodes preserves source order;
    # ast.walk is BFS and would surface siblings before their
    # earlier-in-source nested statements.
    seen: list[dict[str, str]] = []
    seen_pairs: set[tuple[str, str]] = set()

    def visit(n: ast.AST) -> None:
        if isinstance(n, ast.Raise) and n.exc is not None:
            name = _exception_name(n.exc)
            if name:
                msg = _raise_message(n.exc)
                pair = (name, msg)
                if pair not in seen_pairs:
                    seen_pairs.add(pair)
                    seen.append({"class_name": name, "message": msg})
        for child in ast.iter_child_nodes(n):
            visit(child)

    visit(node)
    return seen


def _extract_literal_values(annotation: ast.expr | None) -> list[str] | None:
    """Return the string values of a ``Literal[...]`` annotation, or None.

    Handles both ``Literal["a", "b"]`` and ``typing.Literal["a", "b"]``
    forms. Returns None if the annotation is not a Literal, or if any
    argument is a non-string constant — we only surface enum-like
    string literals since those are what users ask about.
    """
    if annotation is None or not isinstance(annotation, ast.Subscript):
        return None
    value = annotation.value
    name = (
        value.id
        if isinstance(value, ast.Name)
        else (value.attr if isinstance(value, ast.Attribute) else None)
    )
    if name != "Literal":
        return None
    slice_node = annotation.slice
    items = slice_node.elts if isinstance(slice_node, ast.Tuple) else [slice_node]
    out: list[str] = []
    for item in items:
        if isinstance(item, ast.Constant) and isinstance(item.value, str):
            out.append(item.value)
        else:
            return None
    return out


def _extract_param_literals(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> dict[str, list[str]]:
    """Map parameter name -> list of Literal[...] string values."""
    out: dict[str, list[str]] = {}
    all_args = list(node.args.posonlyargs) + list(node.args.args) + list(node.args.kwonlyargs)
    for arg in all_args:
        values = _extract_literal_values(arg.annotation)
        if values:
            out[arg.arg] = values
    return out


def _is_dataclass(node: ast.ClassDef) -> bool:
    """Return True if the class has a ``@dataclass`` decorator."""
    for dec in node.decorator_list:
        if isinstance(dec, ast.Name) and dec.id == "dataclass":
            return True
        if isinstance(dec, ast.Call):
            func = dec.func
            if isinstance(func, ast.Name) and func.id == "dataclass":
                return True
            if isinstance(func, ast.Attribute) and func.attr == "dataclass":
                return True
        if isinstance(dec, ast.Attribute) and dec.attr == "dataclass":
            return True
    return False


def _string_collection_values(node: ast.expr) -> list[str] | None:
    """Return the string values inside a list/tuple/set literal, or None.

    Accepts ``["a", "b"]``, ``("a", "b")``, ``{"a", "b"}``. Returns
    None if any element is not a string constant or the node is not
    a supported collection literal — we deliberately don't surface
    mixed-type collections since users ask about string enums.
    """
    if not isinstance(node, ast.List | ast.Tuple | ast.Set):
        return None
    out: list[str] = []
    for elt in node.elts:
        if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
            out.append(elt.value)
        else:
            return None
    return out


def _extract_module_constant(node: ast.Assign | ast.AnnAssign) -> dict[str, object] | None:
    """Return a structured record for a module-level string constant.

    Recognizes four shapes that users routinely ask about:

    - ``NAME = "value"``
    - ``NAME = ("a", "b")`` / ``["a", "b"]`` / ``{"a", "b"}``
    - ``NAME = frozenset({"a", "b"})`` / ``frozenset(["a", "b"])``
    - ``NAME = set({"a", "b"})``

    Returns ``{"name", "kind", "values"}`` where ``kind`` is one of
    ``str`` / ``tuple`` / ``list`` / ``set`` / ``frozenset``, or
    None if the shape is unrecognized. Non-string-valued constants
    are intentionally skipped — those are runtime config, not the
    string-enum-like constants this extractor surfaces.
    """
    if isinstance(node, ast.Assign):
        if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
            return None
        name = node.targets[0].id
        value = node.value
    else:  # AnnAssign
        if not isinstance(node.target, ast.Name) or node.value is None:
            return None
        name = node.target.id
        value = node.value

    if isinstance(value, ast.Constant) and isinstance(value.value, str):
        return {"name": name, "kind": "str", "values": [value.value]}

    if isinstance(value, ast.Tuple):
        vals = _string_collection_values(value)
        if vals is not None:
            return {"name": name, "kind": "tuple", "values": vals}

    if isinstance(value, ast.List):
        vals = _string_collection_values(value)
        if vals is not None:
            return {"name": name, "kind": "list", "values": vals}

    if isinstance(value, ast.Set):
        vals = _string_collection_values(value)
        if vals is not None:
            return {"name": name, "kind": "set", "values": vals}

    if isinstance(value, ast.Call):
        func = value.func
        call_name = None
        if isinstance(func, ast.Name):
            call_name = func.id
        elif isinstance(func, ast.Attribute):
            call_name = func.attr
        if call_name in ("frozenset", "set") and len(value.args) == 1:
            vals = _string_collection_values(value.args[0])
            if vals is not None:
                return {"name": name, "kind": call_name, "values": vals}
    return None


def _extract_return_data(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> object | None:
    """Return the Python value of a function's literal return, or None.

    Walks the function body in source order for the first ``return``
    statement whose value is a fully-literal dict / list / tuple / set
    / constant (handled via ``ast.literal_eval``). Surfaces
    declarative-config factories — ``get_tools()``,
    ``get_defaults()``, MCP-style tool-schema builders — so the
    polish LLM can render the structure it returns rather than
    hallucinating it from the signature alone. Returns ``None`` if
    the first return is a computed expression (name reference,
    function call, etc.) — we intentionally do not surface partial
    or dynamic returns.
    """
    for child in node.body:
        if not isinstance(child, ast.Return) or child.value is None:
            continue
        value = child.value
        if not isinstance(value, ast.Dict | ast.List | ast.Tuple | ast.Set | ast.Constant):
            return None
        try:
            return ast.literal_eval(value)
        except (ValueError, SyntaxError):
            return None
    return None


def _extract_class_properties(node: ast.ClassDef) -> list[dict[str, str]]:
    """Return ``[{name, return_type, doc}]`` for ``@property`` methods.

    Only captures public properties. Parameterless by definition,
    so no args surfaced. Recognizes the bare ``@property`` form and
    the qualified ``@builtins.property`` / ``@abc.abstractproperty``
    variants that show up in practice.
    """
    props: list[dict[str, str]] = []
    for child in node.body:
        if not isinstance(child, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        if child.name.startswith("_"):
            continue
        if not _has_property_decorator(child):
            continue
        ret = _unparse_annotation(child.returns) if child.returns else ""
        props.append({"name": child.name, "return_type": ret, "doc": _docstring_first_line(child)})
    return props


def _has_property_decorator(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    """Check whether a method has a @property (or variant) decorator."""
    for dec in node.decorator_list:
        if isinstance(dec, ast.Name) and dec.id == "property":
            return True
        if isinstance(dec, ast.Attribute) and dec.attr in ("property", "abstractproperty"):
            return True
    return False


def _extract_dataclass_fields(node: ast.ClassDef) -> list[dict[str, str]]:
    """Return ``[{name, type, default}]`` for each public annotated field.

    Captures every top-level ``AnnAssign`` whose target is a non-underscore
    name. The ``default`` is the unparsed right-hand side (e.g.
    ``"field(default_factory=list)"``) or the empty string when the field
    has no default.
    """
    fields_out: list[dict[str, str]] = []
    for child in node.body:
        if not isinstance(child, ast.AnnAssign) or not isinstance(child.target, ast.Name):
            continue
        name = child.target.id
        if name.startswith("_"):
            continue
        field_type = _unparse_annotation(child.annotation) if child.annotation else ""
        default = _unparse_annotation(child.value) if child.value is not None else ""
        fields_out.append({"name": name, "type": field_type, "default": default})
    return fields_out


def _collect_function(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    rel_path: str,
    info: _SourceInfo,
) -> None:
    first_line = _docstring_first_line(node)
    info.public_functions.append({"name": node.name, "doc": first_line, "file": rel_path})
    info.function_signatures.append(
        {
            "name": node.name,
            "signature": _format_function_signature(node),
            "doc": first_line,
            "file": rel_path,
            "raises": _extract_raises(node),
            "param_literals": _extract_param_literals(node),
            "return_data": _extract_return_data(node),
        }
    )


def _collect_class(
    node: ast.ClassDef,
    rel_path: str,
    info: _SourceInfo,
) -> None:
    first_line = _docstring_first_line(node)
    info.public_classes.append({"name": node.name, "doc": first_line, "file": rel_path})
    is_dc = _is_dataclass(node)
    info.class_signatures.append(
        {
            "name": node.name,
            "methods": _format_class_methods(node),
            "doc": first_line,
            "file": rel_path,
            "is_dataclass": is_dc,
            "dataclass_fields": _extract_dataclass_fields(node) if is_dc else [],
            "properties": _extract_class_properties(node),
        }
    )


def _extract_source_info(
    matched_files: list[str],
    project_root: Path,
) -> _SourceInfo:
    """Extract public API info from Python source files.

    Reads AST to find public functions, classes, and
    module docstrings. Non-Python files are counted
    but not parsed.

    Args:
        matched_files: Relative paths to source files.
        project_root: Project root directory.

    Returns:
        Extracted source information.
    """
    info = _SourceInfo(file_count=len(matched_files))

    for rel_path in matched_files:
        if not rel_path.endswith(".py"):
            continue

        full_path = project_root / rel_path
        try:
            source = full_path.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=rel_path)
        except (OSError, SyntaxError) as e:
            logger.debug("Cannot parse %s: %s", rel_path, e)
            continue

        module_doc = _docstring_first_line(tree)
        if module_doc:
            info.module_docstrings.append(module_doc)

        for node in ast.iter_child_nodes(tree):
            if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                if not node.name.startswith("_"):
                    _collect_function(node, rel_path, info)
            elif isinstance(node, ast.ClassDef):
                if not node.name.startswith("_"):
                    _collect_class(node, rel_path, info)
            elif isinstance(node, ast.Assign | ast.AnnAssign):
                # Module-level string constants — both public and
                # underscore-prefixed, because the leading underscore
                # is the Python convention for "module-private" but
                # the VALUES they hold (allowed tokens, env var
                # names, enum members) are still the kind of detail
                # reference docs answer questions about.
                const = _extract_module_constant(node)
                if const is not None:
                    const["file"] = rel_path
                    info.module_constants.append(const)

    return info


def _format_function_signature(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> str:
    """Format a function AST node as a readable signature.

    Produces ``name(arg1: T1, arg2: T2 = default) -> R`` —
    good enough for the LLM to understand argument types
    and defaults without running a full unparse. Missing
    annotations are omitted rather than replaced with
    ``Any``.

    Args:
        node: AST function node.

    Returns:
        Human-readable signature string.
    """
    args: list[str] = []

    posonly = list(node.args.posonlyargs)
    regular = list(node.args.args)
    kwonly = list(node.args.kwonlyargs)
    defaults = list(node.args.defaults)
    kw_defaults = list(node.args.kw_defaults)

    # Map positional/regular args to their defaults
    positional = posonly + regular
    num_no_default = len(positional) - len(defaults)
    last_posonly_idx = len(posonly) - 1
    for idx, arg in enumerate(positional):
        arg_str = arg.arg
        if arg.annotation is not None:
            arg_str += f": {_unparse_annotation(arg.annotation)}"
        if idx >= num_no_default:
            default = defaults[idx - num_no_default]
            arg_str += f" = {_unparse_annotation(default)}"
        args.append(arg_str)
        if idx == last_posonly_idx:
            args.append("/")

    if node.args.vararg is not None:
        vararg = node.args.vararg
        vararg_str = f"*{vararg.arg}"
        if vararg.annotation is not None:
            vararg_str += f": {_unparse_annotation(vararg.annotation)}"
        args.append(vararg_str)
    elif kwonly:
        args.append("*")

    for kw_arg, kw_default in zip(kwonly, kw_defaults, strict=False):
        kw_str = kw_arg.arg
        if kw_arg.annotation is not None:
            kw_str += f": {_unparse_annotation(kw_arg.annotation)}"
        if kw_default is not None:
            kw_str += f" = {_unparse_annotation(kw_default)}"
        args.append(kw_str)

    if node.args.kwarg is not None:
        kwarg = node.args.kwarg
        kwarg_str = f"**{kwarg.arg}"
        if kwarg.annotation is not None:
            kwarg_str += f": {_unparse_annotation(kwarg.annotation)}"
        args.append(kwarg_str)

    sig = f"{node.name}({', '.join(args)})"
    if node.returns is not None:
        sig += f" -> {_unparse_annotation(node.returns)}"
    return sig


def _format_class_methods(node: ast.ClassDef) -> str:
    """Format a class's public method signatures.

    Returns a newline-separated string of signatures for
    methods whose names do not start with an underscore.
    Includes ``__init__`` because callers need to know the
    constructor shape.

    Args:
        node: AST class node.

    Returns:
        Newline-separated method signatures, or the empty
        string if the class has no public methods.
    """
    methods: list[str] = []
    for child in node.body:
        if isinstance(child, ast.FunctionDef | ast.AsyncFunctionDef):
            name = child.name
            if name.startswith("_") and name != "__init__":
                continue
            # @property methods are surfaced separately via
            # _extract_class_properties — skip here so the
            # polish LLM doesn't render them as callable methods.
            if _has_property_decorator(child):
                continue
            methods.append(_format_function_signature(child))
    return "\n".join(methods)


def _unparse_annotation(node: ast.expr) -> str:
    """Convert an AST expression to a readable string.

    Falls back to ``<expr>`` if ``ast.unparse`` fails so
    signature extraction never raises on exotic annotations.

    Args:
        node: AST expression node.

    Returns:
        Readable string representation.
    """
    try:
        return ast.unparse(node)
    except Exception:  # noqa: BLE001
        # INTENTIONAL: signature extraction is best-effort
        # context for the LLM — never block generation on
        # an exotic annotation we can't render.
        return "<expr>"


def _render_template(
    env: jinja2.Environment,
    feature: Feature,
    depth: str,
    source_hash: str,
    source_info: _SourceInfo,
) -> str:
    """Render a help template using Jinja2 meta templates.

    Args:
        env: Jinja2 environment with template search paths.
        feature: The feature.
        depth: concept, task, or reference.
        source_hash: SHA-256 of source files.
        source_info: Extracted source information.

    Returns:
        Markdown string with YAML frontmatter.
    """
    now = datetime.now(timezone.utc).isoformat()
    title = feature.name.replace("-", " ").replace("_", " ").title()

    # Emit both ``type`` (the canonical field attune-help
    # reads when discriminating template kinds) and ``depth``
    # (legacy field kept for backward compatibility with
    # anything reading older generated output).
    #
    # ``name`` is the human-readable template name and is required
    # by the editor schema. Combining feature + depth keeps the
    # name distinct across features sharing a depth (e.g., two
    # different ``concept`` templates) so editors / retrievers can
    # disambiguate without collisions.
    template_name = f"{feature.name}-{depth}"
    frontmatter = (
        f"---\n"
        f"type: {depth}\n"
        f"name: {template_name}\n"
        f"feature: {feature.name}\n"
        f"depth: {depth}\n"
        f"generated_at: {now}\n"
        f"source_hash: {source_hash}\n"
        f"status: generated\n"
        f"---\n"
    )

    template = env.get_template(f"{depth}.md.j2")
    body = template.render(
        title=title,
        feature_name=feature.name,
        description=feature.description,
        file_patterns=feature.files,
        tags=feature.tags,
        public_classes=source_info.public_classes,
        public_functions=source_info.public_functions,
        module_docstrings=source_info.module_docstrings,
        config_keys=source_info.config_keys,
        file_count=source_info.file_count,
    )

    # Strip trailing whitespace per line to avoid
    # perpetual pre-commit failures
    body = "\n".join(line.rstrip() for line in body.splitlines())

    result = frontmatter + "\n" + body
    if not result.endswith("\n"):
        result += "\n"
    return result
