"""Fact-check finding + report types and soft-fail formatting.

The data shapes here are shared by every check module under
``attune_author.fact_check`` so that callers see one consistent
result envelope regardless of which check produced a finding.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

Severity = Literal["error", "warning"]

#: Stable check-id strings. Kept as constants so config schemas and
#: log lines reference the same canonical names.
CHECK_PYTHON_REFS = "check_python_refs"
CHECK_CLI_REFS = "check_cli_refs"
CHECK_MD_LINKS = "check_md_links"
CHECK_NUMERIC_REFS = "check_numeric_refs"
CHECK_TUTORIAL_STATIC = "check_tutorial_static"
CHECK_DOC_EXAMPLES = "check_doc_examples"


class FactCheckError(Exception):
    """Raised in strict mode when a fact-check report contains errors."""


@dataclass(frozen=True)
class Finding:
    """One issue surfaced by a check.

    Attributes:
        check: Which check produced this finding (one of the
            ``CHECK_*`` constants).
        severity: ``"error"`` (must-fix) or ``"warning"``
            (likely-incorrect-but-unverifiable).
        location: Human-readable position, e.g. ``"Line 17 (prose)"``
            or ``"Line 77 (code fence)"``. Empty string when the
            check is whole-file (numeric counts).
        message: The user-facing explanation. CLI-ref findings
            include the version-coupling block per spec §1.4.
    """

    check: str
    severity: Severity
    location: str
    message: str


@dataclass
class FactCheckReport:
    """Aggregated findings from a fact-check pass over one file.

    The report carries both ``error`` and ``warning`` findings;
    the soft-fail block formatter and the strict-mode gate both
    distinguish on severity.
    """

    findings: list[Finding] = field(default_factory=list)

    def has_errors(self) -> bool:
        """True if any finding has severity ``error``."""
        return any(f.severity == "error" for f in self.findings)

    def extend(self, more: list[Finding]) -> None:
        """Append findings from another check in place."""
        self.findings.extend(more)


@dataclass
class FactCheckConfig:
    """Per-run fact-check configuration.

    Defaults match the spec's "Phase 1 default failure mode is
    soft-fail" — every check enabled, errors written into the
    polished file as an ``## Unresolved references`` block, no
    raise.
    """

    enabled: bool = True
    soft_fail: bool = True
    check_python_refs: bool = True
    check_cli_refs: bool = True
    check_md_links: bool = True
    check_numeric_refs: bool = True
    check_tutorial_static: bool = True
    check_doc_examples: bool = True
    #: Mapping of file path (relative to project root, posix) to
    #: a list of check-id strings that should be skipped for
    #: that file.
    skip: dict[str, list[str]] = field(default_factory=dict)

    def is_check_enabled(self, check: str, file_rel: str | None = None) -> bool:
        """Return True if ``check`` should run for the given file."""
        flag = getattr(self, check, None)
        if flag is False:
            return False
        if file_rel and check in self.skip.get(file_rel, []):
            return False
        return True


def format_unresolved_block(findings: list[Finding]) -> str:
    """Render the soft-fail markdown block for ``findings``.

    Returns an empty string when ``findings`` is empty so the
    caller can use the result as an unconditional suffix.
    """
    if not findings:
        return ""

    lines: list[str] = [
        "",
        "## Unresolved references",
        "",
        "> Auto-generated by attune-author fact-check. Review and either",
        "> fix the source code, fix this doc, or add an override.",
        "",
        "| Location | Severity | Issue |",
        "|---|---|---|",
    ]
    for f in findings:
        location = f.location or "(whole file)"
        # Pipe characters in the message would break the table layout —
        # escape them as the only character that markdown table cells
        # treat specially.
        message = f.message.replace("\n", " ").replace("|", "\\|")
        lines.append(f"| {location} | {f.severity} | {message} |")
    lines.append("")
    return "\n".join(lines)


__all__ = [
    "CHECK_CLI_REFS",
    "CHECK_DOC_EXAMPLES",
    "CHECK_MD_LINKS",
    "CHECK_NUMERIC_REFS",
    "CHECK_PYTHON_REFS",
    "CHECK_TUTORIAL_STATIC",
    "FactCheckConfig",
    "FactCheckError",
    "FactCheckReport",
    "Finding",
    "Severity",
    "format_unresolved_block",
]
